apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus
    targetRevision: 27.5.1
    helm:
      parameters:
        - name: alertmanager.enabled
          value: "false"
        - name: pushgateway.enabled
          value: "false"
        - name: server.service.type
          value: "LoadBalancer"
        - name: server.persistentVolume.enabled
          value: "false"
      releaseName: prometheus
      namespace: monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true