apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: grafana
  namespace: argocd
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: 'grafana-{{name}}'
    spec:
      project: default
      source:
        repoURL: https://grafana.github.io/helm-charts
        chart: grafana
        targetRevision: 8.10.3
        helm:
          parameters:
            - name: service.type
              value: "LoadBalancer"
          releaseName: grafana
          namespace: monitoring
      destination:
        server: '{{server}}'
        namespace: monitoring
      syncPolicy:
        automated:
          prune: true
          selfHeal: true